### ISSUE TITLE
Word classification

### ISSUE THREAD

**Issue by eric-j-ason** [martinlindhe/wordlist_swedish#1]
> Please contact me if you are interested in more advanced data sets, such as full word class relations and more.

That would indeed be nice. For example, for generating passwords or other random strings, having only nouns, in singular form, might look the best, possibly combined with adjectives.

**Comment by martinlindhe** [comment]
Did you have an issue to report or is this just some random words?

**Comment by martinlindhe** [comment]
Feel free to e-mail me if you would like to buy the data set.

**Comment by eric-j-ason** [comment]
Got it. I wasn't aware that it was a business proposition.
